[package]
name = "tokio-async"
version = "0.1.0"
edition = "2021"

[dependencies]
kos = { package = "kos-rs", git = "https://github.com/dreamcast-rs/kos-rs" }
tokio = { version = "1.40.0", features = ["rt", "time", "rt-multi-thread"] }
